name: flutter_rust_net
description: "Independent Flutter + Rust network request library powered by net_engine."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_rust_bridge: 2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  common: ^0.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
