// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> initNetEngine({required NetEngineConfig config}) =>
    RustLib.instance.api.crateApiInitNetEngine(config: config);

Future<ResponseMeta> request({required RequestSpec spec}) =>
    RustLib.instance.api.crateApiRequest(spec: spec);

Future<String> startTransferTask({required TransferTaskSpec spec}) =>
    RustLib.instance.api.crateApiStartTransferTask(spec: spec);

Future<List<NetEvent>> pollEvents({required int limit}) =>
    RustLib.instance.api.crateApiPollEvents(limit: limit);

Future<bool> cancel({required String id}) =>
    RustLib.instance.api.crateApiCancel(id: id);

Future<void> setNetworkBusy({required bool isBusy}) =>
    RustLib.instance.api.crateApiSetNetworkBusy(isBusy: isBusy);

Future<BigInt> clearCache({String? namespace}) =>
    RustLib.instance.api.crateApiClearCache(namespace: namespace);

Future<void> shutdownNetEngine() =>
    RustLib.instance.api.crateApiShutdownNetEngine();

class NetEngineConfig {
  final String baseUrl;
  final int connectTimeoutMs;
  final int readTimeoutMs;
  final int writeTimeoutMs;
  final int maxConnections;
  final int maxConnectionsPerHost;
  final int maxInFlightTasks;
  final int largeBodyThresholdKb;
  final String cacheDir;
  final int cacheDefaultTtlSeconds;
  final int cacheMaxNamespaceBytes;
  final String userAgent;

  const NetEngineConfig({
    required this.baseUrl,
    required this.connectTimeoutMs,
    required this.readTimeoutMs,
    required this.writeTimeoutMs,
    required this.maxConnections,
    required this.maxConnectionsPerHost,
    required this.maxInFlightTasks,
    required this.largeBodyThresholdKb,
    required this.cacheDir,
    required this.cacheDefaultTtlSeconds,
    required this.cacheMaxNamespaceBytes,
    required this.userAgent,
  });

  static Future<NetEngineConfig> default_() =>
      RustLib.instance.api.crateApiNetEngineConfigDefault();

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      connectTimeoutMs.hashCode ^
      readTimeoutMs.hashCode ^
      writeTimeoutMs.hashCode ^
      maxConnections.hashCode ^
      maxConnectionsPerHost.hashCode ^
      maxInFlightTasks.hashCode ^
      largeBodyThresholdKb.hashCode ^
      cacheDir.hashCode ^
      cacheDefaultTtlSeconds.hashCode ^
      cacheMaxNamespaceBytes.hashCode ^
      userAgent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetEngineConfig &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          connectTimeoutMs == other.connectTimeoutMs &&
          readTimeoutMs == other.readTimeoutMs &&
          writeTimeoutMs == other.writeTimeoutMs &&
          maxConnections == other.maxConnections &&
          maxConnectionsPerHost == other.maxConnectionsPerHost &&
          maxInFlightTasks == other.maxInFlightTasks &&
          largeBodyThresholdKb == other.largeBodyThresholdKb &&
          cacheDir == other.cacheDir &&
          cacheDefaultTtlSeconds == other.cacheDefaultTtlSeconds &&
          cacheMaxNamespaceBytes == other.cacheMaxNamespaceBytes &&
          userAgent == other.userAgent;
}

class NetEvent {
  final String id;
  final NetEventKind kind;
  final BigInt transferred;
  final BigInt? total;
  final int? statusCode;
  final String? message;
  final int? costMs;

  const NetEvent({
    required this.id,
    required this.kind,
    required this.transferred,
    this.total,
    this.statusCode,
    this.message,
    this.costMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      transferred.hashCode ^
      total.hashCode ^
      statusCode.hashCode ^
      message.hashCode ^
      costMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          transferred == other.transferred &&
          total == other.total &&
          statusCode == other.statusCode &&
          message == other.message &&
          costMs == other.costMs;
}

enum NetEventKind { queued, started, progress, completed, failed, canceled }

class RequestSpec {
  final String requestId;
  final String method;
  final String path;
  final List<(String, String)> query;
  final List<(String, String)> headers;
  final Uint8List? bodyBytes;
  final String? bodyFilePath;
  final bool expectLargeResponse;
  final String? saveToFilePath;
  final int priority;

  const RequestSpec({
    required this.requestId,
    required this.method,
    required this.path,
    required this.query,
    required this.headers,
    this.bodyBytes,
    this.bodyFilePath,
    required this.expectLargeResponse,
    this.saveToFilePath,
    required this.priority,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      method.hashCode ^
      path.hashCode ^
      query.hashCode ^
      headers.hashCode ^
      bodyBytes.hashCode ^
      bodyFilePath.hashCode ^
      expectLargeResponse.hashCode ^
      saveToFilePath.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestSpec &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          method == other.method &&
          path == other.path &&
          query == other.query &&
          headers == other.headers &&
          bodyBytes == other.bodyBytes &&
          bodyFilePath == other.bodyFilePath &&
          expectLargeResponse == other.expectLargeResponse &&
          saveToFilePath == other.saveToFilePath &&
          priority == other.priority;
}

class ResponseMeta {
  final String requestId;
  final int statusCode;
  final List<(String, String)> headers;
  final Uint8List? bodyInline;
  final String? bodyFilePath;
  final bool fromCache;
  final int costMs;
  final String? error;

  const ResponseMeta({
    required this.requestId,
    required this.statusCode,
    required this.headers,
    this.bodyInline,
    this.bodyFilePath,
    required this.fromCache,
    required this.costMs,
    this.error,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      statusCode.hashCode ^
      headers.hashCode ^
      bodyInline.hashCode ^
      bodyFilePath.hashCode ^
      fromCache.hashCode ^
      costMs.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResponseMeta &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          statusCode == other.statusCode &&
          headers == other.headers &&
          bodyInline == other.bodyInline &&
          bodyFilePath == other.bodyFilePath &&
          fromCache == other.fromCache &&
          costMs == other.costMs &&
          error == other.error;
}

class TransferTaskSpec {
  final String taskId;
  final String kind;
  final String url;
  final String method;
  final List<(String, String)> headers;
  final String localPath;
  final BigInt? resumeFrom;
  final BigInt? expectedTotal;
  final int priority;

  const TransferTaskSpec({
    required this.taskId,
    required this.kind,
    required this.url,
    required this.method,
    required this.headers,
    required this.localPath,
    this.resumeFrom,
    this.expectedTotal,
    required this.priority,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      kind.hashCode ^
      url.hashCode ^
      method.hashCode ^
      headers.hashCode ^
      localPath.hashCode ^
      resumeFrom.hashCode ^
      expectedTotal.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferTaskSpec &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          kind == other.kind &&
          url == other.url &&
          method == other.method &&
          headers == other.headers &&
          localPath == other.localPath &&
          resumeFrom == other.resumeFrom &&
          expectedTotal == other.expectedTotal &&
          priority == other.priority;
}
