// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1854914876;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'net_engine',
    ioDirectory: '../native/rust/net_engine/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiCancel({required String id});

  Future<BigInt> crateApiClearCache({String? namespace});

  Future<void> crateApiInitNetEngine({required NetEngineConfig config});

  Future<NetEngineConfig> crateApiNetEngineConfigDefault();

  Future<List<NetEvent>> crateApiPollEvents({required int limit});

  Future<ResponseMeta> crateApiRequest({required RequestSpec spec});

  Future<void> crateApiSetNetworkBusy({required bool isBusy});

  Future<void> crateApiShutdownNetEngine();

  Future<String> crateApiStartTransferTask({required TransferTaskSpec spec});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiCancel({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCancelConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCancelConstMeta => const TaskConstMeta(
        debugName: "cancel",
        argNames: ["id"],
      );

  @override
  Future<BigInt> crateApiClearCache({String? namespace}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(namespace, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiClearCacheConstMeta,
      argValues: [namespace],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiClearCacheConstMeta => const TaskConstMeta(
        debugName: "clear_cache",
        argNames: ["namespace"],
      );

  @override
  Future<void> crateApiInitNetEngine({required NetEngineConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_net_engine_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitNetEngineConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitNetEngineConstMeta => const TaskConstMeta(
        debugName: "init_net_engine",
        argNames: ["config"],
      );

  @override
  Future<NetEngineConfig> crateApiNetEngineConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_net_engine_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiNetEngineConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetEngineConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "net_engine_config_default",
        argNames: [],
      );

  @override
  Future<List<NetEvent>> crateApiPollEvents({required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_net_event,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPollEventsConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPollEventsConstMeta => const TaskConstMeta(
        debugName: "poll_events",
        argNames: ["limit"],
      );

  @override
  Future<ResponseMeta> crateApiRequest({required RequestSpec spec}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_request_spec(spec, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_response_meta,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRequestConstMeta,
      argValues: [spec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRequestConstMeta => const TaskConstMeta(
        debugName: "request",
        argNames: ["spec"],
      );

  @override
  Future<void> crateApiSetNetworkBusy({required bool isBusy}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(isBusy, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSetNetworkBusyConstMeta,
      argValues: [isBusy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetNetworkBusyConstMeta => const TaskConstMeta(
        debugName: "set_network_busy",
        argNames: ["isBusy"],
      );

  @override
  Future<void> crateApiShutdownNetEngine() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiShutdownNetEngineConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiShutdownNetEngineConstMeta => const TaskConstMeta(
        debugName: "shutdown_net_engine",
        argNames: [],
      );

  @override
  Future<String> crateApiStartTransferTask({required TransferTaskSpec spec}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_transfer_task_spec(spec, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiStartTransferTaskConstMeta,
      argValues: [spec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStartTransferTaskConstMeta => const TaskConstMeta(
        debugName: "start_transfer_task",
        argNames: ["spec"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NetEngineConfig dco_decode_box_autoadd_net_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_net_engine_config(raw);
  }

  @protected
  NetErrorKind dco_decode_box_autoadd_net_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_net_error_kind(raw);
  }

  @protected
  RequestSpec dco_decode_box_autoadd_request_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_request_spec(raw);
  }

  @protected
  TransferTaskSpec dco_decode_box_autoadd_transfer_task_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transfer_task_spec(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<NetEvent> dco_decode_list_net_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_net_event).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  NetEngineConfig dco_decode_net_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return NetEngineConfig(
      baseUrl: dco_decode_String(arr[0]),
      connectTimeoutMs: dco_decode_u_32(arr[1]),
      readTimeoutMs: dco_decode_u_32(arr[2]),
      writeTimeoutMs: dco_decode_u_32(arr[3]),
      maxConnections: dco_decode_u_16(arr[4]),
      maxConnectionsPerHost: dco_decode_u_16(arr[5]),
      maxInFlightTasks: dco_decode_u_16(arr[6]),
      largeBodyThresholdKb: dco_decode_u_32(arr[7]),
      cacheDir: dco_decode_String(arr[8]),
      cacheDefaultTtlSeconds: dco_decode_u_32(arr[9]),
      cacheMaxNamespaceBytes: dco_decode_u_32(arr[10]),
      userAgent: dco_decode_String(arr[11]),
    );
  }

  @protected
  NetErrorKind dco_decode_net_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetErrorKind.values[raw as int];
  }

  @protected
  NetEvent dco_decode_net_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NetEvent(
      id: dco_decode_String(arr[0]),
      kind: dco_decode_net_event_kind(arr[1]),
      transferred: dco_decode_u_64(arr[2]),
      total: dco_decode_opt_box_autoadd_u_64(arr[3]),
      statusCode: dco_decode_opt_box_autoadd_u_16(arr[4]),
      message: dco_decode_opt_String(arr[5]),
      costMs: dco_decode_opt_box_autoadd_u_32(arr[6]),
    );
  }

  @protected
  NetEventKind dco_decode_net_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NetEventKind.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NetErrorKind? dco_decode_opt_box_autoadd_net_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_net_error_kind(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  RequestSpec dco_decode_request_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RequestSpec(
      requestId: dco_decode_String(arr[0]),
      method: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      query: dco_decode_list_record_string_string(arr[3]),
      headers: dco_decode_list_record_string_string(arr[4]),
      bodyBytes: dco_decode_opt_list_prim_u_8_strict(arr[5]),
      bodyFilePath: dco_decode_opt_String(arr[6]),
      expectLargeResponse: dco_decode_bool(arr[7]),
      saveToFilePath: dco_decode_opt_String(arr[8]),
      priority: dco_decode_u_8(arr[9]),
    );
  }

  @protected
  ResponseMeta dco_decode_response_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ResponseMeta(
      requestId: dco_decode_String(arr[0]),
      statusCode: dco_decode_u_16(arr[1]),
      headers: dco_decode_list_record_string_string(arr[2]),
      bodyInline: dco_decode_opt_list_prim_u_8_strict(arr[3]),
      bodyFilePath: dco_decode_opt_String(arr[4]),
      fromCache: dco_decode_bool(arr[5]),
      costMs: dco_decode_u_32(arr[6]),
      errorKind: dco_decode_opt_box_autoadd_net_error_kind(arr[7]),
      error: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  TransferTaskSpec dco_decode_transfer_task_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TransferTaskSpec(
      taskId: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      url: dco_decode_String(arr[2]),
      method: dco_decode_String(arr[3]),
      headers: dco_decode_list_record_string_string(arr[4]),
      localPath: dco_decode_String(arr[5]),
      resumeFrom: dco_decode_opt_box_autoadd_u_64(arr[6]),
      expectedTotal: dco_decode_opt_box_autoadd_u_64(arr[7]),
      priority: dco_decode_u_8(arr[8]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NetEngineConfig sse_decode_box_autoadd_net_engine_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_net_engine_config(deserializer));
  }

  @protected
  NetErrorKind sse_decode_box_autoadd_net_error_kind(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_net_error_kind(deserializer));
  }

  @protected
  RequestSpec sse_decode_box_autoadd_request_spec(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_request_spec(deserializer));
  }

  @protected
  TransferTaskSpec sse_decode_box_autoadd_transfer_task_spec(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transfer_task_spec(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<NetEvent> sse_decode_list_net_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NetEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_net_event(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  NetEngineConfig sse_decode_net_engine_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_baseUrl = sse_decode_String(deserializer);
    var var_connectTimeoutMs = sse_decode_u_32(deserializer);
    var var_readTimeoutMs = sse_decode_u_32(deserializer);
    var var_writeTimeoutMs = sse_decode_u_32(deserializer);
    var var_maxConnections = sse_decode_u_16(deserializer);
    var var_maxConnectionsPerHost = sse_decode_u_16(deserializer);
    var var_maxInFlightTasks = sse_decode_u_16(deserializer);
    var var_largeBodyThresholdKb = sse_decode_u_32(deserializer);
    var var_cacheDir = sse_decode_String(deserializer);
    var var_cacheDefaultTtlSeconds = sse_decode_u_32(deserializer);
    var var_cacheMaxNamespaceBytes = sse_decode_u_32(deserializer);
    var var_userAgent = sse_decode_String(deserializer);
    return NetEngineConfig(
        baseUrl: var_baseUrl,
        connectTimeoutMs: var_connectTimeoutMs,
        readTimeoutMs: var_readTimeoutMs,
        writeTimeoutMs: var_writeTimeoutMs,
        maxConnections: var_maxConnections,
        maxConnectionsPerHost: var_maxConnectionsPerHost,
        maxInFlightTasks: var_maxInFlightTasks,
        largeBodyThresholdKb: var_largeBodyThresholdKb,
        cacheDir: var_cacheDir,
        cacheDefaultTtlSeconds: var_cacheDefaultTtlSeconds,
        cacheMaxNamespaceBytes: var_cacheMaxNamespaceBytes,
        userAgent: var_userAgent);
  }

  @protected
  NetErrorKind sse_decode_net_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NetErrorKind.values[inner];
  }

  @protected
  NetEvent sse_decode_net_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kind = sse_decode_net_event_kind(deserializer);
    var var_transferred = sse_decode_u_64(deserializer);
    var var_total = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_statusCode = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_costMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    return NetEvent(
        id: var_id,
        kind: var_kind,
        transferred: var_transferred,
        total: var_total,
        statusCode: var_statusCode,
        message: var_message,
        costMs: var_costMs);
  }

  @protected
  NetEventKind sse_decode_net_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NetEventKind.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NetErrorKind? sse_decode_opt_box_autoadd_net_error_kind(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_net_error_kind(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RequestSpec sse_decode_request_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requestId = sse_decode_String(deserializer);
    var var_method = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_query = sse_decode_list_record_string_string(deserializer);
    var var_headers = sse_decode_list_record_string_string(deserializer);
    var var_bodyBytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_bodyFilePath = sse_decode_opt_String(deserializer);
    var var_expectLargeResponse = sse_decode_bool(deserializer);
    var var_saveToFilePath = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_u_8(deserializer);
    return RequestSpec(
        requestId: var_requestId,
        method: var_method,
        path: var_path,
        query: var_query,
        headers: var_headers,
        bodyBytes: var_bodyBytes,
        bodyFilePath: var_bodyFilePath,
        expectLargeResponse: var_expectLargeResponse,
        saveToFilePath: var_saveToFilePath,
        priority: var_priority);
  }

  @protected
  ResponseMeta sse_decode_response_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requestId = sse_decode_String(deserializer);
    var var_statusCode = sse_decode_u_16(deserializer);
    var var_headers = sse_decode_list_record_string_string(deserializer);
    var var_bodyInline = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_bodyFilePath = sse_decode_opt_String(deserializer);
    var var_fromCache = sse_decode_bool(deserializer);
    var var_costMs = sse_decode_u_32(deserializer);
    var var_errorKind = sse_decode_opt_box_autoadd_net_error_kind(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ResponseMeta(
        requestId: var_requestId,
        statusCode: var_statusCode,
        headers: var_headers,
        bodyInline: var_bodyInline,
        bodyFilePath: var_bodyFilePath,
        fromCache: var_fromCache,
        costMs: var_costMs,
        errorKind: var_errorKind,
        error: var_error);
  }

  @protected
  TransferTaskSpec sse_decode_transfer_task_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_method = sse_decode_String(deserializer);
    var var_headers = sse_decode_list_record_string_string(deserializer);
    var var_localPath = sse_decode_String(deserializer);
    var var_resumeFrom = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_expectedTotal = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_priority = sse_decode_u_8(deserializer);
    return TransferTaskSpec(
        taskId: var_taskId,
        kind: var_kind,
        url: var_url,
        method: var_method,
        headers: var_headers,
        localPath: var_localPath,
        resumeFrom: var_resumeFrom,
        expectedTotal: var_expectedTotal,
        priority: var_priority);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_net_engine_config(
      NetEngineConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_net_engine_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_net_error_kind(
      NetErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_net_error_kind(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_request_spec(
      RequestSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_request_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transfer_task_spec(
      TransferTaskSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transfer_task_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_net_event(
      List<NetEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_net_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_net_engine_config(
      NetEngineConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_u_32(self.connectTimeoutMs, serializer);
    sse_encode_u_32(self.readTimeoutMs, serializer);
    sse_encode_u_32(self.writeTimeoutMs, serializer);
    sse_encode_u_16(self.maxConnections, serializer);
    sse_encode_u_16(self.maxConnectionsPerHost, serializer);
    sse_encode_u_16(self.maxInFlightTasks, serializer);
    sse_encode_u_32(self.largeBodyThresholdKb, serializer);
    sse_encode_String(self.cacheDir, serializer);
    sse_encode_u_32(self.cacheDefaultTtlSeconds, serializer);
    sse_encode_u_32(self.cacheMaxNamespaceBytes, serializer);
    sse_encode_String(self.userAgent, serializer);
  }

  @protected
  void sse_encode_net_error_kind(NetErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_net_event(NetEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_net_event_kind(self.kind, serializer);
    sse_encode_u_64(self.transferred, serializer);
    sse_encode_opt_box_autoadd_u_64(self.total, serializer);
    sse_encode_opt_box_autoadd_u_16(self.statusCode, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_32(self.costMs, serializer);
  }

  @protected
  void sse_encode_net_event_kind(NetEventKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_net_error_kind(
      NetErrorKind? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_net_error_kind(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_request_spec(RequestSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.requestId, serializer);
    sse_encode_String(self.method, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_list_record_string_string(self.query, serializer);
    sse_encode_list_record_string_string(self.headers, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.bodyBytes, serializer);
    sse_encode_opt_String(self.bodyFilePath, serializer);
    sse_encode_bool(self.expectLargeResponse, serializer);
    sse_encode_opt_String(self.saveToFilePath, serializer);
    sse_encode_u_8(self.priority, serializer);
  }

  @protected
  void sse_encode_response_meta(ResponseMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.requestId, serializer);
    sse_encode_u_16(self.statusCode, serializer);
    sse_encode_list_record_string_string(self.headers, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.bodyInline, serializer);
    sse_encode_opt_String(self.bodyFilePath, serializer);
    sse_encode_bool(self.fromCache, serializer);
    sse_encode_u_32(self.costMs, serializer);
    sse_encode_opt_box_autoadd_net_error_kind(self.errorKind, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_transfer_task_spec(
      TransferTaskSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.method, serializer);
    sse_encode_list_record_string_string(self.headers, serializer);
    sse_encode_String(self.localPath, serializer);
    sse_encode_opt_box_autoadd_u_64(self.resumeFrom, serializer);
    sse_encode_opt_box_autoadd_u_64(self.expectedTotal, serializer);
    sse_encode_u_8(self.priority, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
